### PR TITLE
Review MS track and acq stats

### PR DESCRIPTION
**Pull request by taldcroft**
This branch picked up some extra commits, but I think they are at least marginally related.  I'm good for merge if you are @jeanconn .

### CODE REVIEW

**Comment by taldcroft** [comment]
The updated acq_probs provides necessary (and hopefully sufficient) documentation that the MS-disabled model is predicting on-board behavior accurately.  And, importantly, that the on-board behavior is quite good now and the OBC does successfully identify most stars in the 10 to 10.7 range.

**Comment by jeanconn** [comment]
Regarding the overall PR, this gets changes to analysis_plots to ignore defective pixel... should we stick a note somewhere mentioning that the analysis_plots helpers all have multiple star set to "False" (which is equivalent to respecting the multiple star filter).  I just don't know where I'd look for such a note.

**Comment by jeanconn** [comment]
And thanks for the updated notebook.  If you think that this does deserve a bit more attention, I'll work on some text for the starcheck release and link the notebook from the twiki release page.

**Comment by taldcroft** [comment]
Hmm, maybe the `ms_flag` default should now be `None`?  Since I don't know where to look for a note now, maybe we just assume that our future-selves will look at the code.

**Comment by jeanconn** [comment]
OK, I'll just go through and set the new default.  I can't think of a use
case for that code that would want the old default.

**Comment by taldcroft** [comment]
Yes, a reference to the notebook in the release notes would be good.  Your email announce (for the starcheck update) should highlight the slightly unusual nature of this update and also point to the notebook for validation of the model update.

**Comment by jeanconn** [comment]
> OK, I'll just go through and set the new default.  I can't think of a use
> case for that code that would > want the old default.

Well, except for making the previous analysis plots.
​

**Comment by taldcroft** [comment]
I hope we won't be fussing about with that too much any more.

**Pull request merged**
